/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerSlugRouteImport } from './routes/$customerSlug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CaptureFrameIdRouteImport } from './routes/capture.$frameId'
import { Route as ResultFrameIdRouteImport } from './routes/result.$frameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSlugRoute = CustomerSlugRouteImport.update({
  id: '/$customerSlug',
  path: '/$customerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureFrameIdRoute = CaptureFrameIdRouteImport.update({
  id: '/capture/$frameId',
  path: '/capture/$frameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultFrameIdRoute = ResultFrameIdRouteImport.update({
  id: '/result/$frameId',
  path: '/result/$frameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/capture/$frameId': typeof CaptureFrameIdRoute
  '/result/$frameId': typeof ResultFrameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/capture/$frameId': typeof CaptureFrameIdRoute
  '/result/$frameId': typeof ResultFrameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/capture/$frameId': typeof CaptureFrameIdRoute
  '/result/$frameId': typeof ResultFrameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$customerSlug'
    | '/admin'
    | '/login'
    | '/capture/$frameId'
    | '/result/$frameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$customerSlug'
    | '/admin'
    | '/login'
    | '/capture/$frameId'
    | '/result/$frameId'
  id:
    | '__root__'
    | '/'
    | '/$customerSlug'
    | '/admin'
    | '/login'
    | '/capture/$frameId'
    | '/result/$frameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerSlugRoute: typeof CustomerSlugRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  CaptureFrameIdRoute: typeof CaptureFrameIdRoute
  ResultFrameIdRoute: typeof ResultFrameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$customerSlug': {
      id: '/$customerSlug'
      path: '/$customerSlug'
      fullPath: '/$customerSlug'
      preLoaderRoute: typeof CustomerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$frameId': {
      id: '/capture/$frameId'
      path: '/capture/$frameId'
      fullPath: '/capture/$frameId'
      preLoaderRoute: typeof CaptureFrameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$frameId': {
      id: '/result/$frameId'
      path: '/result/$frameId'
      fullPath: '/result/$frameId'
      preLoaderRoute: typeof ResultFrameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerSlugRoute: CustomerSlugRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  CaptureFrameIdRoute: CaptureFrameIdRoute,
  ResultFrameIdRoute: ResultFrameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
