/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerSlugRouteImport } from './routes/$customerSlug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SharedSessionsTokenRouteImport } from './routes/shared-sessions.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSlugRoute = CustomerSlugRouteImport.update({
  id: '/$customerSlug',
  path: '/$customerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedSessionsTokenRoute = SharedSessionsTokenRouteImport.update({
  id: '/shared-sessions/$token',
  path: '/shared-sessions/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/shared-sessions/$token': typeof SharedSessionsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/shared-sessions/$token': typeof SharedSessionsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$customerSlug': typeof CustomerSlugRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/shared-sessions/$token': typeof SharedSessionsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$customerSlug' | '/admin' | '/login' | '/shared-sessions/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$customerSlug' | '/admin' | '/login' | '/shared-sessions/$token'
  id:
    | '__root__'
    | '/'
    | '/$customerSlug'
    | '/admin'
    | '/login'
    | '/shared-sessions/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerSlugRoute: typeof CustomerSlugRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SharedSessionsTokenRoute: typeof SharedSessionsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$customerSlug': {
      id: '/$customerSlug'
      path: '/$customerSlug'
      fullPath: '/$customerSlug'
      preLoaderRoute: typeof CustomerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-sessions/$token': {
      id: '/shared-sessions/$token'
      path: '/shared-sessions/$token'
      fullPath: '/shared-sessions/$token'
      preLoaderRoute: typeof SharedSessionsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerSlugRoute: CustomerSlugRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SharedSessionsTokenRoute: SharedSessionsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
